
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: royal_liquor_app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.royalbeverages.rule=Host(`royal-beverages.20.244.0.92.nip.io`)"
      - "traefik.http.routers.royalbeverages.entrypoints=websecure"
      - "traefik.http.routers.royalbeverages.tls.certresolver=myresolver"
      - "traefik.http.services.royalbeverages.loadbalancer.server.port=80"
      - "traefik.docker.network=global-proxy-net"

    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=pgbouncer
      - DB_PORT=6432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASS=${DB_PASS:-18499}
      - DB_NAME=${DB_NAME:-royal-liquor}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - rl_network
      - global-proxy-net

  db:
    image: postgres:15-alpine
    container_name: royal_liquor_db

    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASS:-18499}
      - POSTGRES_DB=${DB_NAME:-royal-liquor}
    volumes:
      - db_data:/var/lib/postgresql/data
      # Map the schema files so they automatically execute when the database is created
      - ./database/schema.sql:/docker-entrypoint-initdb.d/02_schema.sql
      - ./database/seed_data.sql:/docker-entrypoint-initdb.d/03_seed_data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rl_network

  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: royal_liquor_pgbouncer

    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASS:-18499}
      - AUTH_TYPE=scram-sha-256
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=1000
      - DEFAULT_POOL_SIZE=20
      - LISTEN_PORT=6432
    depends_on:
      db:
        condition: service_healthy
    networks:
      - rl_network

volumes:
  db_data:

networks:
  rl_network:
    driver: bridge
  global-proxy-net:
    external: true
